#ifndef BLANIEL_H
#define BLANIEL_H

/* Auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

bool blaniel_init(const char *api_url, const char *api_key, uint64_t timeout_ms);

void blaniel_cleanup(void);

char *blaniel_last_error(void);

void blaniel_free_string(char *s);

char *blaniel_health(void);

char *blaniel_get_npc(const char *npc_id);

char *blaniel_chat(const char *npc_id, const char *message);

char *blaniel_move_npc(const char *npc_id, double x, double y, double z, const char *world);

char *blaniel_navigate_to(const char *npc_id, const char *target_name);

char *blaniel_navigate_to_coords(const char *npc_id,
                                 double x,
                                 double y,
                                 double z,
                                 const char *world);

char *blaniel_pathfind(const char *npc_id,
                       double from_x,
                       double from_y,
                       double from_z,
                       double to_x,
                       double to_y,
                       double to_z,
                       const char *world);

char *blaniel_get_nearby_npcs(double x, double y, double z, double radius, const char *world);

char *blaniel_get_navigation_config(const char *npc_id);

char *blaniel_set_navigation_config(const char *npc_id, const char *config_json);

char *blaniel_register_scene(const char *scene_json);

char *blaniel_get_action_config(const char *npc_id);

char *blaniel_set_action_config(const char *npc_id, const char *config_json);

char *blaniel_list_llm_providers(void);

char *blaniel_get_llm_presets(void);

char *blaniel_register_llm_provider(const char *provider_type,
                                    const char *api_key,
                                    const char *model,
                                    const char *base_url);

char *blaniel_unregister_llm_provider(const char *name);

char *blaniel_get_llm_provider_status(const char *name);

char *blaniel_ambient_dialogue(const char *participant_ids_json, const char *context);

char *blaniel_get_action_catalog(void);

#endif /* BLANIEL_H */
