[package]
name = "npc-db"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

npc-types = { path = "../types" }

[dev-dependencies]
dotenvy.workspace = true
